package gui;

import models.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.util.ArrayList;

public class HospitalRecordManager extends javax.swing.JFrame {
    // Data
    private static ArrayList<Patient> patientList = new ArrayList<>();
    private static Hospital hospital;
    private static HospitalRecordManager instance;
    private static Hospital currentHospital;
    
    
    // UI Components - Preserving your exact variable names
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable patientTable;
    private javax.swing.JLabel lblHospitalName;
    private javax.swing.JLabel lblHospitalCapacity;
    private javax.swing.JLabel lblHospitalState;


    public HospitalRecordManager() {
        initComponents();
        instance = this;
    if(currentHospital == null) {
            // Initialize with default values if not set
            currentHospital = new Hospital("Unnamed Hospital", 50, "Unknown State");
        }
        refreshHospitalData();
    }

     public static Hospital getCurrentHospital() {
        return currentHospital;
    }
      public static void setCurrentHospital(Hospital hospital) {
        currentHospital = hospital;
        if(instance != null) {
            instance.refreshHospitalData();
        }
    }
       private void refreshHospitalData() {
        if(currentHospital != null) {
            // Make sure these labels exist in your form
            if(lblHospitalName != null) {
                lblHospitalName.setText("Hospital: " + currentHospital.getName());
            }
            if(lblHospitalCapacity != null) {
                lblHospitalCapacity.setText("Capacity: " + currentHospital.getMaxPatients());
            }
            if(lblHospitalState != null) {
                lblHospitalState.setText("State: " + currentHospital.getState());
            }
            
            // Refresh any patient tables or other UI elements
            refreshPatientTable();
        }
    }
    private void setupTable() {
        patientTable.setModel(new DefaultTableModel(
            new Object[][]{},
            new String[]{"Name", "Age", "Gender", "Condition", "Type", "Location"}
        ));
    }

    private void setupFilters() {
        // Clear existing items
        jComboBox2.removeAllItems();
        jComboBox1.removeAllItems();
        
        // Add patient types
        jComboBox2.addItem("All");
        jComboBox2.addItem("Inpatient");
        jComboBox2.addItem("Outpatient");
        jComboBox2.addItem("Emergency");
        
        // Add hospital blocks
        jComboBox1.addItem("All");
        if (hospital != null) {
            for (HospitalBlock block : hospital.getBlocks()) {
                jComboBox1.addItem(block.getBlockName());
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel1.setText("Hospital Patient Record System");

        jButton1.setText("Add Patient");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit Hospitol Information");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        patientTable.setToolTipText("");
        jScrollPane1.setViewportView(patientTable);

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel2.setText("Patient List");

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel3.setText("Search & Filter :");

        jLabel4.setText("Filter By Block : ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Filter By Patient Type : ");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Show search result ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jComboBox2, 0, 244, Short.MAX_VALUE)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(818, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(109, 109, 109)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(315, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
 NewPatient newPatientWindow = new NewPatient(this);
newPatientWindow.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     HospitalInformation hospitalInfo = new HospitalInformation();
     hospitalInfo.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String selectedBlock = jComboBox1.getSelectedItem().toString();
        String selectedType = jComboBox2.getSelectedItem().toString();
        
        DefaultTableModel model = (DefaultTableModel) patientTable.getModel();
        model.setRowCount(0);
        
        for (Patient p : patientList) {
            boolean blockMatch = selectedBlock.equals("All") || 
                               p.getLocation().getBlockName().equals(selectedBlock);
            boolean typeMatch = selectedType.equals("All") || 
                               p.getClass().getSimpleName().equals(selectedType);
            
            if (blockMatch && typeMatch) {
                model.addRow(new Object[]{
                    p.getName(),
                    p.getAge(),
                    p.getGender(),
                    p.getCondition(),
                    p.getClass().getSimpleName(),
                    p.getLocation().getBlockName()
                });
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed
 // Data Methods
   
    public static void addPatient(Patient patient) {
        patientList.add(patient);
        refreshTable();
    }
    private void refreshPatientTable() {
    // Get the table model (assuming patientTable is your JTable variable name)
    DefaultTableModel model = (DefaultTableModel) patientTable.getModel();
    
    // Clear existing rows
    model.setRowCount(0);
    
    // Get current hospital instance
    Hospital hospital = getCurrentHospital();
    
    // Check if hospital exists and has patients
    if (hospital != null && patientList != null) {
        // Add each patient to the table
        for (Patient patient : patientList) {
            Object[] rowData = new Object[] {
                patient.getName(),
                patient.getAge(),
                patient.getGender(),
                patient.getCondition(),
                patient.getClass().getSimpleName(), // Shows "Inpatient", "Outpatient", etc.
                patient.getLocation() != null ? patient.getLocation().getBlockName() : "N/A"
            };
            model.addRow(rowData);
        }
    }
    
    // Optional: Auto-resize columns after refresh
    for (int i = 0; i < patientTable.getColumnCount(); i++) {
        patientTable.getColumnModel().getColumn(i).setPreferredWidth(150);
    }
}
    public JTable getPatientTable() {
    return patientTable;
}
    public static void setHospital(Hospital h) {
        hospital = h;
        if (instance != null) {
            instance.setupFilters();
        }
    }

    public static void refreshTable() {
        if (instance != null) {
            instance.jButton4ActionPerformed(null);
        }
    }
      public static void main(String args[]) {
        // Initialize sample data
        Hospital hospital = new Hospital("General Hospital", 100, "New York");
        hospital.addBlock(new HospitalBlock("A", 1, "Cardiology"));
        hospital.addBlock(new HospitalBlock("B", 2, "Pediatrics"));
        
        setHospital(hospital);
        
        java.awt.EventQueue.invokeLater(() -> {
            HospitalRecordManager manager = new HospitalRecordManager();
            manager.setSize(1000, 600);
            manager.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            manager.setVisible(true);
        });
    }


    /**
     * @param args the command line

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable patientTable;
    // End of variables declaration//GEN-END:variables

**/
}